---
jobs:
- name: test-unit
  serial: true
  plan:
  - get: builder-src
    trigger: true
  - task: test
    file: builder-src/ci/tasks/test-unit.yml

- name: publish-ubuntu-hvm
  serial: true
  plan:
  - aggregate:
    - get: builder-src
      passed: [test-unit]
    - get: builder-config
  - get: input-stemcell
    resource: ubuntu-stemcell
    trigger: true
  - task: build
    file: builder-config/tasks/build.yml
    params:
      ami_description: {{publish_ami_description}}
      ami_virtualization_type: hvm
      ami_visibility: {{publish_ami_visibility}}
      ami_region: {{publish_region}}
      ami_access_key: {{publish_access_key}}
      ami_secret_key: {{publish_secret_key}}
      ami_bucket_name: {{publish_bucket}}
      ami_server_side_encryption: AES256
  - put: light-stemcell
    params:
      file: light-stemcell/light-bosh-stemcell-*.tgz
  on_failure:
    put: slack
    params: &slack-params
      text: |
        :x: FAILED to build light stemcell
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: {{slack_channel}}
      username: {{slack_username}}
      icon_url: {{slack_icon_url}}
  on_success:
    put: slack
    params:
      <<: *slack-params
      text: |
        :white_check_mark: Successfully built light stemcell
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>

resources:
- name: builder-src
  type: git
  source:
    uri: {{builder_src_git_url}}
    branch: {{builder_src_git_branch}}

- name: builder-config
  type: git
  source:
    uri: {{builder_config_git_url}}
    branch: {{builder_config_git_branch}}

- name: ubuntu-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    force_regular: true

- name: light-stemcell
  type: s3
  source:
    regexp: light-bosh-stemcell-([\d\.]+)-.*\.tgz
    access_key_id: {{output_bucket_access_key}}
    secret_access_key: {{output_bucket_secret_key}}
    bucket: {{output_bucket}}
    region_name: {{output_region}}
    server_side_encryption: AES256

- name: slack
  type: slack-notification
  source:
    url: {{slack_webhook_url}}

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
