---
platform: linux
image: docker:///boshcpi/aws-light-stemcell-builder
inputs:
- name: builder-src
- name: input-stemcell
outputs:
- name: light-stemcell
run:
  path: builder-src/ci/tasks/build.sh
params:
  ami_description: replace-me
  ami_virtualization_type: replace-me
  ami_visibility: replace-me
  us_ami_region: replace-me
  us_ami_access_key: replace-me
  us_ami_secret_key: replace-me
  us_ami_bucket_name: replace-me
  us_ami_destinations: replace-me
  cn_ami_region: replace-me
  cn_ami_access_key: replace-me
  cn_ami_secret_key: replace-me
  cn_ami_bucket_name: replace-me
