---
platform: linux
image: docker:///boshcpi/aws-light-stemcell-builder
inputs:
- name: builder-src
- name: input-stemcell
outputs:
- name: light-stemcell
run:
  path: builder-src/ci/tasks/build.sh
params:
  region: replace-me
  access_key: replace-me
  secret_key: replace-me
  bucket_name: replace-me
  copy_dests: replace-me
  ami_description: replace-me
  ami_virtualization_type: replace-me
  ami_visibility: replace-me
