---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/aws-light-stemcell-builder}
inputs:
- name: builder-src
- name: input-stemcell
outputs:
- name: converted-stemcell
run:
  path: builder-src/ci/tasks/convert-stemcell.sh
