---
platform: linux
image: docker:///boshcpi/aws-light-stemcell-builder
inputs:
- name: builder-src
- name: heavy-stemcell-in
run:
  path: builder-src/ci/tasks/run-integration.sh
params:
  access_key: replace-me
  secret_key: replace-me
  bucket_name: replace-me
  region: replace-me
  ami_fixture_id: replace-me
