---
platform: linux
image: docker:///boshcpi/aws-light-stemcell-builder
inputs:
- name: builder-src
run:
  path: builder-src/ci/tasks/test-integration.sh
params:
  access_key:                 ""
  secret_key:                 ""
  bucket_name:                ""
  region:                     ""
  copy_region:                ""
  cn_access_key:              ""
  cn_secret_key:              ""
  cn_bucket_name:             ""
  cn_region:                  ""
