---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/aws-copy-ami}
inputs:
- name: builder-src
- name: raw-machine-image
outputs:
- name: metadata
run:
  path: builder-src/ci/ami_to_raw_image/tasks/publish.sh
params:
  ami_description:         ""
  ami_virtualization_type: ""
  ami_visibility:          ""
  ami_initial_region:      ""
  ami_copy_regions:        ""
  ami_access_key:          ""
  ami_secret_key:          ""
  ami_bucket_name:         ""
