---
jobs:
  - name: test-unit
    serial: true
    plan:
      - get: builder-src
        trigger: true
      - task: test
        file: builder-src/ci/tasks/test-unit.yml

  - name: publish-ubuntu-hvm
    serial: true
    plan:
      - get: builder-src
      - get: input-stemcell
        resource: ubuntu-stemcell
        version: every
        trigger: true
      - task: build
        file: builder-src/ci/tasks/build.yml
        params:
          ami_description: {{publish__ami_description}}
          ami_virtualization_type: hvm
          ami_visibility: {{publish__ami_visibility}}
          ami_region: {{publish__us_region}}
          ami_access_key: {{publish__us_access_key}}
          ami_secret_key: {{publish__us_secret_key}}
          ami_bucket_name: {{publish__us_bucket}}
      - put: light-stemcell
        params:
          file: light-stemcell/light-bosh-stemcell-*.tgz

resources:
  - name: builder-src
    type: git
    source:
      uri: https://github.com/18F/cg-aws-light-stemcell-builder
      branch: master
  - name: ubuntu-stemcell
    type: s3
    source:
      bucket: bosh-jenkins-artifacts
      regexp: bosh-stemcell/aws/bosh-stemcell-([0-9\.]+)-aws-xen-ubuntu-trusty-go_agent\.tgz
  - name: light-stemcell
    type: s3
    source:
      regexp: light-bosh-stemcell-([\d\.]+)-.*\.tgz
      access_key_id: {{output__bucket_access_key}}
      secret_access_key: {{output__bucket_secret_key}}
      bucket: {{output__bucket}}
      region_name: {{s3_region}}
      endpoint: {{s3_endpoint}}
