---
groups:
  - name: light-stemcell-builder
    jobs:
      - test-unit
      - promote

  - name: publishing
    jobs:
      - convert-ubuntu-stemcell
      - publish-ubuntu-hvm

jobs:
  - name: test-unit
    serial: true
    plan:
      - get: builder-src
        resource: builder-src-in
        trigger: true
      - task: test
        file: builder-src/ci/tasks/test-unit.yml

  - name: promote
    plan:
      - aggregate:
        - get: builder-src
          passed: [test-unit]
          resource: builder-src-in
          trigger: true
        - get: version-semver
          params: { bump: patch }
      - put: version-semver
        params: { file: version-semver/number }
      - put: builder-src-out
        params: { repository: builder-src }

  - name: convert-ubuntu-stemcell
    serial: true
    plan:
      - aggregate:
        - get: builder-src
          resource: builder-src-out
          trigger: false
        - get: input-stemcell
          resource: ubuntu-stemcell
          version: every
          trigger: true
      - task: convert
        file: builder-src/ci/tasks/convert-stemcell.yml
      - put: converted-ubuntu-stemcell
        params:
          from: converted-stemcell/bosh-stemcell-(.*).tgz

  - name: publish-ubuntu-hvm
    serial: true
    plan:
      - get: builder-src
        resource: builder-src-out
        trigger: false
      - get: input-stemcell
        resource: converted-ubuntu-stemcell
        passed: [convert-ubuntu-stemcell]
        version: every
        trigger: true
      - task: build
        file: builder-src/ci/tasks/build.yml
        params:
          ami_description: {{publish__ami_description}}
          ami_virtualization_type: hvm
          ami_visibility: {{publish__ami_visibility}}
          ami_region: {{publish__us_region}}
          ami_access_key: {{publish__us_access_key}}
          ami_secret_key: {{publish__us_secret_key}}
          ami_bucket_name: {{publish__us_bucket}}
      - put: light-stemcell
        params:
          from: light-stemcell/light-bosh-stemcell-(.*).tgz

  - name: bump-minor
    public: true
    plan:
      - get: version-semver
        params: { bump: minor }
      - put: version-semver
        params: { file: version-semver/number }

  - name: bump-major
    public: true
    plan:
      - get: version-semver
        params: { bump: major }
      - put: version-semver
        params: { file: version-semver/number }

resources:
  - name: builder-src-in
    type: git
    source:
      uri: git@github.com:18F/cg-aws-light-stemcell-builder.git
      branch: develop
      private_key: {{builder__github_deployment_key}}

  - name: builder-src-out
    type: git
    source:
      uri: git@github.com:18F/cg-aws-light-stemcell-builder.git
      branch: master
      private_key: {{builder__github_deployment_key}}

  - name: version-semver
    type: semver
    source:
      initial_version: 0.0.1
      key: current-version
      access_key_id: {{builder__access_key}}
      secret_access_key: {{builder__secret_key}}
      bucket: {{builder__bucket}}
      region_name: {{s3_region}}
      endpoint: {{s3_endpoint}}

  - name: ubuntu-stemcell
    type: s3
    source:
      regexp: bosh-stemcell/aws/bosh-stemcell-([0-9\.]+)-aws-xen-ubuntu-trusty-go_agent\.tgz
      bucket: bosh-jenkins-artifacts

  - name: converted-ubuntu-stemcell
    type: s3
    source:
      regexp: bosh-stemcell-([0-9\.]+)-aws-xen-ubuntu-trusty-go_agent\.tgz
      access_key_id: {{converted__bucket_access_key}}
      secret_access_key: {{converted__bucket_secret_key}}
      bucket: {{converted__bucket}}
      region_name: {{s3_region}}
      endpoint: {{s3_endpoint}}

  - name: light-stemcell
    type: s3
    source:
      regexp: light-bosh-stemcell-([\d\.]+)-.*\.tgz
      access_key_id: {{output__bucket_access_key}}
      secret_access_key: {{output__bucket_secret_key}}
      bucket: {{output__bucket}}
      region_name: {{s3_region}}
      endpoint: {{s3_endpoint}}
